### ISSUE TITLE
local secondary index

### ISSUE THREAD

**Issue by lcdiaz2106** [lakindu2002/terraform-dynamodb#1]
Hello
can you add some code to add LSI ?
Because I test with some indexes and I have this error

`Error: error creating DynamoDB Table: ValidationException: One or more parameter values were invalid: Some index key attributes are not defined in AttributeDefinitions.`
Not sure what to do here, in the official doc there is no info about AttributeDefinitions
let me know
Many thanks

**Comment by lakindu2002** [comment]
Hi @lcdiaz2106 , you are running into this issue because you probably added a new range key that you have not already defined as a Attribute. Therefore, what you can do is, add your new range key to your `AttributeDefinitions` as shown below.

```
 attribute {
    name = "newRangeKey"
    type = "S"
  }
```

Then try deploying the LSI by adding the `local_secondary_index` attribute.
Lemme know if this works and if not, I'll add some supporting code in the repo.

**Comment by lcdiaz2106** [comment]
Yes it works.
But now I face other issue, I'm not able to create the sort key
This is my complete code
`resource "aws_dynamodb_table" "gap-audit-results" {
  name           = "${var.application}-${var.app_environment}-gap-audit-results"
  billing_mode     = "PAY_PER_REQUEST"
//  read_capacity  = var.read_capacity
//  write_capacity = var.write_capacity
  hash_key       = "AuditResultsParitionKey"
  range_key      = "CategoryIdProductIdLinkNameResultId"

  attribute {
    name = "AuditResultsParitionKey"
    type = "S"
  }

  attribute {
    name = "CategoryIdProductIdLinkNameResultId"
    type = "S"
  }

attribute {
    name = "AuditTypeResultId"
    type = "S"
  }

local_secondary_index {
  name = "AuditTypeResultIdIndex"
  range_key = "AuditResultsPartitionKey"
  projection_type = "INCLUDE"
  non_key_attributes = ["AuditTypeResultId"]
}

point_in_time_recovery {    enabled = var.point_in_time_recovery_enabled  }
server_side_encryption {    enabled = var.server_side_encryption_enabled  }

tags = var.dynamodb-tags

}
`

And what is asked is
this table 


DT1 |   | gap-audit-results | AuditResultsParitionKey (String) | CategoryIdProductIdLinkNameResultId  (String)
-- | -- | -- | -- | --



with this index


IDX1 | AuditTypeResultIdIndex(LSI) | AuditResultsPartitionKey (String) | AuditTypeResultId (String)
-- | -- | -- | --

**Comment by lakindu2002** [comment]
What the error you're getting here @lcdiaz2106

**Comment by lakindu2002** [comment]
I looked at your code, and I think from my initial observation it should work find. Is there any error when you mean "Im not able to create the sort key" @lcdiaz2106

**Comment by lakindu2002** [comment]
@lcdiaz2106 

In the LSI you've specified the range key as `AuditResultsPartitionKey`. However, you've not defined this as an attribute. There is a typo. You've added `AuditResultsParitionKey` to your Attributes, not `AuditResultsPartitionKey`.  So the reason that you cannot create the sort key (aka -> attribute) is because the attribute you're defining is not used in the primary hash/range key or LSI hash/range key or GSI hash/range key. The attributes you defined must be used as a key in either your table, or indexes.

**Comment by lakindu2002** [comment]
@lcdiaz2106 check if the explanation I've added above works for you :)

**Comment by lcdiaz2106** [comment]
Hello
Yes, it works !! many thanks for your help ! Have a nice day

**Comment by lcdiaz2106** [comment]
Super support. MANY THANKS !

**Comment by lakindu2002** [comment]
> Hello
> Yes, it works !! many thanks for your help ! Have a nice day

Glad to help, if there’s anything, do reach out

**Comment by lakindu2002** [comment]
> Super support. MANY THANKS !

No worries, happy to help you out. If there’s anything do reach out to me

**Comment by lcdiaz2106** [comment]
Hello
I have an other issue yes. Maybe you can help
I would like to have automatic backup of the dynamoDB tables. Is it possible with terraform?
In the code I have this:
point_in_time_recovery {    enabled = var.point_in_time_recovery_enabled  }

But when I go to console and click on a table and then navigate to the backup tab, it's empty.. Do you face this situation before?
let me know

**Comment by lakindu2002** [comment]
Hi @lcdiaz2106 
So, DynamoDB offers two kinds of backups.
1. Point in time recovery 
2. Backups using AWS Backup.

You can use point in time recovery to recover data of up to 35 days. To enable it simply add the following config to your table. 

```
point_in_time_recovery { enabled = true }

```

**Comment by lcdiaz2106** [comment]
Ok
I had this code
point_in_time_recovery {    enabled = var.point_in_time_recovery_enabled  }
I replace by yours and now it works, so I guess I have an issue with variables
Thanks again !

**Comment by lakindu2002** [comment]
> Ok
> I had this code
> point_in_time_recovery { enabled = var.point_in_time_recovery_enabled }
> I replace by yours and now it works, so I guess I have an issue with variables
> Thanks again !

Awesome, no worries. Try checking the variable (perhaps there's a typo in it)
